baseURL = "/"                        
languageCode = "de"
defaultContentLanguage = "de"
title = "VGNSMS"                       # site title 
theme = "zozo"
hasCJKLanguage = false                 # has chinese/japanese/korean ?  
summaryLength = 30
paginate = 4                           # shows the number of articles  
enableEmoji = true
googleAnalytics = "UA-191242278-1"     # your google analytics id
disqusShortname = "disqus_OlLLFboZ76"                   # your discuss shortname

# [outputs]
#  home = ["HTML", "RSS", "JSON"]

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                    
  name = "Jens"

[blackfriday]                          # markdown interpreter, see: https://github.com/russross/blackfriday
  smartypants = false

[[menu.main]]                          # config your menu  
 # name = "Home"
 # weight = 10
 # identifier = "home"
 # url = "/"
[[menu.main]]                       # wieder aktivieren, sobald Kontent auf der Seite ist
  name = "Alle Posts"
  weight = 30
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Kategorien"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Über"
  weight = 20
  identifier = "about"
  url = "/about/"

[params]
  subTitle = ": der; Subst. mask."                                       # site's subTitle  
  footerSlogan = "Eine Seite für Betroffene"                             # site's footer slogan  
  keywords = ["Veganismus","Ethik","Umweltschutz","Konsumkritik"]        # site's keywords  
  description = "Ein persönlicher Blog über Veganismus."                 # site's description 
  enableMathJax = true                                                   # enable mathjax  
  enableSummary = true                                                   # display the article summary  
  mainSections = ["posts","post"]
  customCSS = ["custom.css"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
 github = "https://github.com/js32"
 # twitter = " "
 # facebook = " "
 # weibo = " "
 # instagram = " "
  mail = "mailto:dieses.veganismus@posteo.jp"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    enableDNT = true
    simple = true
  [privacy.youtube]
    privacyEnhanced = true