baseURL = "dcsalmfdskfmskmfklsddlasdlm.netlify.app"
languageCode = "de"
defaultContentLanguage = "de"
title = "VGNSM"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "Jens"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
 # name = "Home"
 # weight = 10
 # identifier = "home"
 # url = "/"
[[menu.main]]
  name = "Archiv"
  weight = 230
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Über"
  weight = 20
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "Veganismus, der | Substantiv maskulin"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "Eine Seite für Betroffene"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Veganismus","Ethik","Umweltschutz"]                                  # site's keywords  # 网站关键字
  description = "Ein persönlicher Blog über Veganismus."                        # site's description  # 网站描述
  enableMathJax = false                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
 # github = " "
 # twitter = " "
 # facebook = " "
 # weibo = " "
 # instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
