[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true" 

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
	from = "/*"
	to = "/n2ckvspvxvg5fhss9hyxuj5sdoqhx8g7spmj7yn7m95htyjdpy9o7bzjay5ip6r3upmxbn44mf4935wwvw6ruq7eprprovdepitohavvwmfyw9v2c64uxbmcrrw34nu3/"
	status = 404


# Caching:

#[[headers]]
#  for = "/static/images/*"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"
#[[headers]]
#  for = "/css/*.css"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"
#[[headers]]
#  for = "/js/*.js"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"

