[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.84.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true" 

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.84.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.84.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.84.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"




# Caching:

#[[headers]]
#  for = "/static/images/*"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"
#[[headers]]
#  for = "/css/*.css"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"
#[[headers]]
#  for = "/js/*.js"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"

