[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.122.0"


[[redirects]]
	from = "/js/script.js"
	to = "https://analytics.kiste.limo/js/plausible.js"
	status = 200
[[redirects]]
	from = "/api/event"
	to = "https://analytics.kiste.limo/api/event"
	status = 202

[[redirects]]
	from = "/*"
	to = "/n2ckvspvxvg5fhss9hyxuj5sdoqhx8g7spmj7yn7m95htyjdpy9o7bzjay5ip6r3upmxbn44mf4935wwvw6ruq7eprprovdepitohavvwmfyw9v2c64uxbmcrrw34nu3/"
	status = 404

[[redirects]]
	from = "/categories/"
	to = "/tags/"
	status = 301
	force = true
  	headers = {X-From = "Netlify"}


# Caching:

#[[headers]]
#  for = "/static/images/*"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"
#[[headers]]
#  for = "/css/*.css"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"
#[[headers]]
#  for = "/js/*.js"
#  [headers.values]
#    Cache-Control = "public, max-age=604800, immutable"

